### ISSUE TITLE
Executing notebooks

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#1]
Right now, I think the notebook -> html script just renders the current output stored in the notebook. I believe the old version actually executed the notebook to ensure that the output correctly reflected the input in each cell. 

Can we bring that back? We'll also need to store the data files used in the notebooks somewhere. Seems like this repo should contain the canonical source of the notebooks, which means it also needs the tools that execute them.

**Comment by SamLau95** [comment]
Actually, we just used `nbconvert` before which just renders the current output (https://github.com/dsten/text/blob/c97b735c9148aef3723d05d68b9b13948f112c11/setup.py#L80).

I don't know of a simple way to evaluate the output from the input in a simple way off the top of my head. Do you happen to know?

I moved the data files into the `notebooks` folder so theoretically the `read_table` calls should work as before.

**Comment by papajohn** [comment]
Ok, we can just continue executing from within the notebook. Thanks for
migrating. Sounds like this issue is closed.
