### ISSUE TITLE
8.5 graphics all give warning messages about deprecations

### ISSUE THREAD

**Issue by debbieyuster** [data-8/textbook#128]
All the graphics (histograms & maps) on the [section 8.5 page](https://www.inferentialthinking.com/chapters/08/5/Bike_Sharing_in_the_Bay_Area.html) give warning messages, such as:
```
/home/choldgraf/anaconda/envs/dev/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
```
The graphics do render.

**Comment by papajohn** [comment]
This is a https://github.com/data-8/datascience issue. Closing here and opening https://github.com/data-8/datascience/issues/494
