### ISSUE TITLE
Update textbook for latest jupyter book

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#131]
There is [now a new version of jupyter book](https://jupyterbook.org) that is much-improved. It will require some modification of the current textbook to get it working.

I have done most of the heavy lifting for this here: https://github.com/data-8/textbook/tree/book_update

However, there are some things that should be done to make it work. I'm happy to help any student teams figure this out:

1. Check each page to make sure that markdown headers are sequential. For example:

   This is sequential:
   ```
   # Header 1
   
   Content
   
   ## Header 2

   Content
   ```
   

   This is not sequential: 
   ```
   # Header 1
   
   Content
   
   ### Header 2

   Content
   ```

2. Re-run each notebook to make sure it still runs properly, and re-populate the outputs. Some notebooks are out-of-date and don't run correctly.
3. Make sure each page has a title that starts with a single `#` character
4. Re-work our auto-deploy infrastructure to use the new jupyter book build system

Let me know if I can be helpful in figuring this out. It would be good to make the switch sooner than later, because the version of jupyter book we're using no longer has support, and because the new build system will be both better and easier to understand.

**Comment by davidwagner** [comment]
Thank you for all of your work on this, @choldgraf!   I've gone through everything to address points 1,2,3 above:

-  All headers are now consecutive. 

- Each file now starts with a title that starts with a first-level header, i.e., either `# ` or with the `====` syntax (which I think is equivalent).

- In notebooks, the first cell might be a code block that produces no output, then a Markdown cell with a first-level header.  It looks like that is ok; if not, let me know.

- I re-ran all notebooks.

Some issues that will need to be taken care of:

1. I'll need your help re-working the auto-deploy infrastructure.  I don't know how the current stuff works.

2. We lost the chapter numbers.  We refer to particular chapter numbers, and I suspect others outside Berkeley might do that too.  We need to avoid changing the numbering of chapters, as that will break those references.  The Introduction should be unnumbered (or Chapter 0), then the chapters should start with Chapter 1 is "Data Science" and so on.  How do we preserve that?

3. I think it might be important to avoid breaking links to the chapters. It looks like the names got changed (e.g., capital letters instead of lowercase, dashes instead of underlines).  Can we control that?  Or maybe we can add redirects on the website?

4. We need the static CSV files to appear at inferentialthinking.org/data/ to avoid breaking existing notebooks, both in the textbook and in class.  How do we do that?

5. The styling is different.  For instance, inline code is now red whereas code blocks look normal.  There is also this weird right-hand-side floating table-of-contents of the current page, which isn't present in the current book and isn't useful in my opinion and just takes up space and shoves the content into a narrow column.  The maps are getting shoved into this small scrolling viewport; see e.g. Chapter 8.5.  It'd be nice to fix these.

6. Some of the Latex isn't getting recognized.  See, e.g,. the formulas under Chapter 9.5, "When All Outcomes Are Equally Likely" or the end of Chapter 14.6.

7. The image `array_subtraction.png` referenced in Chapter 5.3 (More on Arrays) didn't get copied over.

8. The table at the end of Chapter 14.3 didn't show up properly.

9. Cells marked `# HIDDEN` still show up.  Perhaps I just remove `# HIDDEN`?  Do I need a particular tag in the cell metadata?

I haven't tried to fix 6-9 myself yet; perhaps those will be straightforward.

**Comment by choldgraf** [comment]
Hey David. Are there any student teams working ok the data 8 infra? That's what other courses have done, I'm happy to speak with some of them about how they could try tackling these things. I'm out in paternity leave for some time so will be relatively unresponsive but happy to help guide.

**Comment by davidwagner** [comment]
Thanks, Chris!  Thank you for your support -- much appreciated.  I'm the lead on this; I can delegate some tasks to students if I understand what needs to be done, but maybe you could speak to me about what approaches I could take or any advice you might have, and I'll delegate whatever I can't handle?  Congratulations on your kid!

**Comment by choldgraf** [comment]
Cool, I'll write up some responses to your questions when I have a moment between diapers

**Comment by choldgraf** [comment]
> either # or with the ==== syntax (which I think is equivalent).

This is roughly true, but not quite. While rST will dynamically assign levels to header characters on a per-page basis, markdown I believe has a strict 1-to-1 mapping. As a general rule, you should start any pages with setext headers (`====`, `----`, `~~~~`, etc) with `====`, then `----`.

> In notebooks, the first cell might be a code block that produces no output, then a Markdown cell with a first-level header. It looks like that is ok; if not, let me know.

Yep that should be fine.

> I'll need your help re-working the auto-deploy infrastructure. I don't know how the current stuff works.

First the book structure needs to be updated according to the new `toc` structure and `config` structure.

- [jupyter book docs on new toc structure](https://jupyterbook.org/customize/toc.html)
- [jupyter book docs on new config structure](https://jupyterbook.org/customize/config.html)

> We lost the chapter numbers. We refer to particular chapter numbers, and I suspect others outside Berkeley might do that too. We need to avoid changing the numbering of chapters, as that will break those references. The Introduction should be unnumbered (or Chapter 0), then the chapters should start with Chapter 1 is "Data Science" and so on. How do we preserve that?

Try the pattern described here: https://jupyterbook.org/customize/toc.html#number-your-book-s-chapters-and-sections

Does that work? 

> I think it might be important to avoid breaking links to the chapters. It looks like the names got changed (e.g., capital letters instead of lowercase, dashes instead of underlines). Can we control that? Or maybe we can add redirects on the website?

Hmmm - you could add re-directs for this, either manually for each page, or using something like [this redirects sphinx extension](https://github.com/wpilibsuite/sphinxext-rediraffe). And see [the customizing sphinx docs](https://jupyterbook.org/advanced/sphinx.html) for how you could enable extra Sphinx extensions in Jupyter Book.

> We need the static CSV files to appear at inferentialthinking.org/data/ to avoid breaking existing notebooks, both in the textbook and in class. How do we do that?

For this you can manually configure Sphinx to copy over the assets you want. Check out the instructions in this PR here: https://github.com/executablebooks/jupyter-book/pull/916

> The styling is different. For instance, inline code is now red whereas code blocks look normal.

Some styling has changed - if you'd like to manually update some of it, check out these docs on using your own CSS rules: https://jupyterbook.org/advanced/sphinx.html#custom-css-or-javascript

> There is also this weird right-hand-side floating table-of-contents of the current page, which isn't present in the current book and isn't useful in my opinion and just takes up space and shoves the content into a narrow column. The maps are getting shoved into this small scrolling viewport; see e.g. Chapter 8.5. It'd be nice to fix these.

I'm not quite sure what you mean. There's a table of contents in the current version too for me:
 
![image](https://user-images.githubusercontent.com/1839645/91619409-d1c95480-e941-11ea-9664-139f3417ec0b.png)

Can you post a screenshot of what you are seeing? Or provide a link to a minimal book setup that recreates the issue that I can look at?

> Some of the Latex isn't getting recognized. See, e.g,. the formulas under Chapter 9.5, "When All Outcomes Are Equally Likely" or the end of Chapter 14.6.

The safest thing to do is wrap any math in `$$` characters. It's hard for me to debug this because I don't have access to a successfully building book (see my comment above).

That said, in general check out [the jupyter book math docs](https://jupyterbook.org/content/math.html#math-blocks) for guides on this.

> The image array_subtraction.png referenced in Chapter 5.3 (More on Arrays) didn't get copied over.

That's becuause the image is manually linked with HTML instead of with a markdown image syntax (`![](path)`). I believe in an upcoming release of Jupyter Book we *will* copy over images specified with `<img>` but it's not active right now.

> The table at the end of Chapter 14.3 didn't show up properly.

This is another one that is hard to debug without a minimal book to reproduce the bug. Let me know when there is one (or when this repository will build with `jupyter-book build .`)

> Cells marked # HIDDEN still show up. Perhaps I just remove # HIDDEN? Do I need a particular tag in the cell metadata?

You can remove the `# HIDDEN` and add a `hide-cell` or `remove-cell` tag to any cell you'd like to remove. For a helper script that shows you how to do this all at once, perhaps this will be useful: https://jupyterbook.org/advanced/advanced.html#add-tags-to-notebook-cells-based-on-their-content

**Comment by choldgraf** [comment]
One other note - you may want to speak with Ani as I know she has a student who is helping her update the prob140 book to the new Jupyter Book structure...perhaps they'd be able to provide help if I am unresponsive?

**Comment by davidwagner** [comment]
Awesome!  Thank you for the detailed information!  That made it easy for me to make a lot of progress on this.  I have a book that builds without errors.  I've updated the _toc and _config files.  Seems everything is fine with the URLs; I don't know why I thought it was a problem.  I got the static assets taken care of.

I now understand what is going on with the right-hand page navbar.  On the current textbook built with the old Jupyter Book, if the browser window is narrower than the width of the rendered page, only the left part is visible (so the right-hand navbar isn't visible).  When building with the new Jupyter book, the style uses some kind of responsive design and shrinks the center column with the text of the book to make space for the right-hand navbar.  This is maybe not ideal as there's a lot of wasted white space, but I'm going to categorize that as an issue for CSS/styling.  Sample screenshot:

![navbars](https://user-images.githubusercontent.com/3349841/92076965-6384f780-ed70-11ea-8899-b20a59d0cb7c.png)

I'll continue working on the other items.  I think I know what to do for most of them.  I won't know how to update the auto-deploy infrastructure or CSS, but I think I have ideas for things to try for everything else.

**Comment by davidwagner** [comment]
TODO for myself:

[ ] Update all notebooks to refer to ../assets/data/ rather than ../data, and rerun notebooks
[ ] Fix Latex formulas under Chapter 9.5, "When All Outcomes Are Equally Likely"
[ ] Fix Latex formulas at the end of Chapter 14.6
[ ] Fix reference to image array_subtraction.png in Chapter 5.3 (More on Arrays) 
[ ] Fix table at the end of Chapter 14.3 
[ ] Replace all #HIDDEN cells with a tag in cell metadata, and rerun those notebooks
[ ] Look into CSS styling
[ ] Test binder links (might need to wait until this is pushed)

**Comment by choldgraf** [comment]
Nice! Glad that this helped. re: the CSS thing you mentioned, the TOC will hide itself when the screen is narrow enough, it might just be that your screen is just above that threshold?

> Figure out how to get Interact button back

This should be helpful: https://jupyterbook.org/interactive/launchbuttons.html#binder-buttons-for-your-pages

LMK when you push the changes to this repository and I can update the auto-deploy scripts

**Comment by davidwagner** [comment]
@choldgraf I think I'm finally ready for auto-deploy scripts.  I have a version in git that builds cleanly and has most of what I want.  (I don't want to deploy yet -- there will be a few more small changes before I want to deploy -- but I'm close, and I'd be interested to know how to push the button to deploy when it's ready to go.)  Could you update the auto-deploy scripts when you have a chance?

**Comment by choldgraf** [comment]
is there a branch that has the updated book? It'll be easiest if I can have a branch to work from to make sure it works etc.

**Comment by davidwagner** [comment]
Same branch: `book_update`

**Comment by choldgraf** [comment]
Cool - I have a PR to do this here: #140 let me know what you think

**Comment by choldgraf** [comment]
I've just opened #156 which I believe also escalates this in importance as one way to resolve it. To re-iterate here **any updates to the book will need to be manually made [to the HTML here](https://github.com/inferentialthinking/inferentialthinking.github.io) until we update or fix the book infrastructure**.

I'll leave it to others to decide whether it is better to manually edit HTML for the rest of the semester, or to try and finish the JB upgrade mid-semester (which may be jarring, as the design of the book will [use the new jupyter book style](https://jupyterbook.org), but maybe it'd be worth it?)

If people decide they definitely want to make the update to the new Jupyter Book, I can make myself available for an hour or two to push it through.

**Comment by papajohn** [comment]
I'm going to try updating the infrastructure this week. I don't think the formatting change will be a problem.

Thanks for all the pointers, @choldgraf. I'll let you know when I get stuck.

**Comment by choldgraf** [comment]
@papajohn sounds good, please let me know if you'd like some help, I think everybody's life will be easier once the book infrastructure is updated and we can once again deploy changes without hand-coding HTML 😬

**Comment by papajohn** [comment]
@choldgraf Is `staticman.yml` necessary anymore?  I think I can delete it; I don't see how it's used, if at all.

FIle: https://github.com/data-8/textbook/blob/book_update/staticman.yml
Commit: https://github.com/data-8/textbook/commit/e57fb5b3483ce208c858fbeb80f83d70567fc5f1

**Comment by choldgraf** [comment]
nope - not used anymore 👍

**Comment by papajohn** [comment]
@choldgraf The `book_update` branch now builds, addresses all the issues discussed in this thread (except perhaps Binder links, but those can be fixed later), and contains all of the content changes from the last year. Therefore, I think it's ready to become the new `main` branch and serve as the source for the textbook. 

Any chance you want to deploy it and set it up to auto-deploy in the future? I could try, but I'm sure I'll break something.

**Comment by choldgraf** [comment]
Yep, i can give it a shot as long as I have the instructors blessing that it's ok for the public facing book to change slightly mid semester. You think that's ok?

**Comment by choldgraf** [comment]
Sounds like we have a 🟢 - I'll try doing this today or tomorrow 👍

**Comment by choldgraf** [comment]
OK @papajohn - I believe that the new book is now live and correctly updating! Want to push a change to `main` to confirm for yourself that it does, in fact, work? :-)

**Comment by papajohn** [comment]
Works perfectly! Thank you!
