### ISSUE TITLE
Interact links broken due to matplotlib backend change

### ISSUE THREAD

**Issue by mdogy** [data-8/textbook#139]
The datascience libraries were broken for a time because matplotlib has dropped support for the warn=False optional argument in the "use" function which picks the backend renders. It was deprecated in 3.1 and now that it is 3.3 they have made it breaking. The datascience libraries are about to push removal of this so that their libraries will import but at this time one has to pull directly from the repo.

Unfortunately that won't totally fix the notebooks because code like
matplotlib.use('Agg', warn=False)
is in the import cell as well. These have to be purged in the notebooks to read
matplotlib.use('Agg')
or the interact functionality will not work.

**Comment by mdogy** [comment]
Got this message from @davidwagner 

https://github.com/data-8/datascience/issues/445 
closed:

"datascience 0.15.8 should fix this. Update with pip."

environment of texbook needs to reflect and explicit uses of warn=False in matplotlib.use need purging.

**Comment by papajohn** [comment]
Fixed.
