### ISSUE TITLE
Switch main branch of the repository to `main` instead of `master` when we update the book

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#141]
Right now the new book is at `book_update`. It might be complex to merge this into our master branch since that'll be a gigantic merge conflict.

Perhaps a simpler approach would be to use this opportunity to make the default branch `main` instead of `master` and just switch over the branch for the new book, rather than trying to merge it in. Basically the steps to take would be:

- Update #140 to use `main` not `master` as its trigger branch
- When `book_update` is ready, make a new branch off of it called `main`
- In the repo settings, make the "base" branch to be `main` instead of `master`
- Probably rename `master` to `old-book` or something like this

@davidwagner what do you think?

**Comment by Yanay1** [comment]
Just looking back through issues-- are we able to make updates to the textbook? Additionally, who is maintaining the repo right now?

**Comment by choldgraf** [comment]
I think that's a question for @davidwagner

**Comment by choldgraf** [comment]
This is now fixed! Many thanks @papajohn for helping push this through 👍
