### ISSUE TITLE
Any possible CSS

### ISSUE THREAD

**Issue by polygons** [data-8/textbook#145]
I was able to make book and build book with no errors. However, there is no layout or design when I load it to server. 
Here is a sample page: http://skylinedatascience.org/book/chapters/01/what-is-data-science.html

Could you please tell me what I am missing here?

Thanks,
k1

**Comment by ericvd-ucb** [comment]
Hi Kayvan @polygons  - not sure what happened - I think your question is more directed towards Jupyterbook  than the Data 8 people.  However I will say that for your case we would just recommend using the textbook from https://www.inferentialthinking.com/chapters/intro and not building your own

**Comment by polygons** [comment]
Thanks, Eric.

**Comment by davidwagner** [comment]
Our build infrastructure is broken right now, so if you try to build the book yourself, probably something will go awry.  We don't have capacity to support this right now -- sorry.  Hopefully using the existing textbook will be sufficient.
