### ISSUE TITLE
Chapter 7 interact not working in Binder - folium import

### ISSUE THREAD

**Issue by ericvd-ucb** [data-8/textbook#146]
When I hit the Interact link for Chapter 7 the import statement ran into a problem with Folium

**Comment by mycarta** [comment]
I am having the same issue with chapter 9, which is reading material for Section 2 of Data8.2x on edX.

<img width="900" alt="Screen Shot 2020-11-24 at 7 46 39 PM" src="https://user-images.githubusercontent.com/7424763/100176939-5a4a8900-2e8e-11eb-9302-103ab5a6870e.png">

**Comment by papajohn** [comment]
Fixed by the new version of the book, I believe.
