### ISSUE TITLE
Interact doesn't seem to work

### ISSUE THREAD

**Issue by davidwagner** [data-8/textbook#150]
A student reports that 'interact' doesn't work.  They get the following error message:

```
ImportError: cannot import name 'BeautifyIcon' from 'folium.plugins' (/srv/conda/envs/notebook/lib/python3.7/site-packages/folium/plugins/__init__.py)
```

**Comment by papajohn** [comment]
I tried the bike maps demo (which includes folium calls) under the new version of the book and a map appeared.
