### ISSUE TITLE
Chapter 11 reinforces racist beliefs

### ISSUE THREAD

**Issue by tkphd** [data-8/textbook#154]
The lynching of Robert Swain should not be taken lightly, and that is the case in this textbook.
For context, please review a recent thread on Twitter, and overhaul the chapter accordingly.

https://twitter.com/rangerriri/status/1366955779270402050

The material in question was most recently modified by @choldgraf, @a-adhikari, @debbieyuster, and @davidwagner. Provenance before e57fb5b gets dicey.

**Comment by tkphd** [comment]
@choldgraf signaled reluctance to revise the contents, deferring to the original authors. Per the [site](https://www.inferentialthinking.com/chapters/intro.html), that would seem to be @a-adhikari and @papajohn.

**Comment by tkphd** [comment]
Disappointed that this request for growth was closed without comment. Your students deserve much better.

**Comment by papajohn** [comment]
No, the issue was closed because I updated the textbook.

https://github.com/data-8/textbook/commit/99c9bc5d9942f05e4f4782df15bc04a53f10183e

We've also communicated with all of the students in the course and Rina in particular, of course.

**Comment by tkphd** [comment]
My mistake! I didn't see a reference, and assumed the worst. Thank you for taking action @papajohn.
