### ISSUE TITLE
The book will not deploy until it is either updated or the deploy infra is fixed

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#156]
Currently the deployment infrastructure for this repository is about 2 years old and is no longer functional. A number of degradations have happened -

- Jupyter Book has changed significantly and the current deploy scripts no longer work
- CircleCI stopped building the repository and the deployment scripts will need to be fixed
- We'll also need to get them working for the last version of JB that worked before the major overhaul (I believe the 0.6 series)
- Finally we will need to update the deployment key infrastructure because I think CircleCI has lost that information.

**We will not be able to automatically deploy changes to https://github.com/inferentialthinking/inferentialthinking.github.io until this is resolved**. The only way to edit the books content without these fixes is to change the HTML that is stored there.

**Another alternative** is to finish the upgrade of this book infrastructure to the new version of Jupyter Book. This is discussed in #131 with an implementation on the `book_update` branch, and #140 adding in the deploy script.

**Comment by choldgraf** [comment]
This is now fixed! Many thanks @papajohn for helping push this through 👍

**Comment by papajohn** [comment]
Thank you!
