### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by sharonwsolis** [data-8/textbook#161]
doesn't work with the updated textbook links

**Comment by davidwagner** [comment]
Looks like a fix is to change the mybinder link to change `...main?urlpath=tree/chapters...` to `...main?filepath=chapters...`

**Comment by davidwagner** [comment]
I can't figure out how to troubleshoot this.  Anyone have any ideas what might be causing this or how to fix it?

**Comment by davidwagner** [comment]
Fixed now, see #184

**Comment by davidwagner** [comment]
Closing

**Comment by davidwagner** [comment]
Closing
