### ISSUE TITLE
Invalid Certificate for www.inferentialthinking.com

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#162]
For some reason, inferentialthinking.com works fine, but www.inferentialthinking.com has an invalid certificate. If anyone knows about certificates and would like to guide me to the right instructions for fixing the problem, I'd appreciate it.

**Comment by cycomachead** [comment]
How's the site setup? GitHub pages, some static server?
Unless you've changed something the `www` redirects now to the naked domain, and doesn't throw an error in the process, so I think it's all good. If you were trying to set that up, then the DNS provider may have just been slow to generate the cert.

**Comment by papajohn** [comment]
I don't seem to be able to replicate the problem. I'll close it for now.
