### ISSUE TITLE
Name 'read_url' is not defined

### ISSUE THREAD

**Issue by madindehead** [data-8/textbook#164]
Sorry this probably isn't the best place to ask, but I cannot find anywhere else to look. 

I'm currently looking at working my way through the Data8 course at home using my own self-hosted Jupyer Lab. 
I've tried the 'Plotting the Classics's example which uses the 'read_url' function. 

Everytime I try the example - on both my TLJH install and Anaconda, I get the error

`NameError: name 'read_url' is not defined`

While I've found a few examples of how to actual define this name, I have no idea where to even place it. I assumed that the datascience module would take care of this? If anyone has any ideas or can point me in the correct direction, I would be very grateful. Right now it's just causing me immense frustration as the textbook doesn't say that anything beyond datascience, pandas etc. is required.

Thanks.

**Comment by adnanhemani** [comment]
So if you take a look at the ipynb file for the chapter [here](https://github.com/data-8/textbook/blob/main/chapters/01/3/Plotting_the_Classics.ipynb), you'll see it's a custom defined function in the header cell that we've hidden for the purposes of readability of the textbook. Ping back on this issue if you have any issues on using this :)

**Comment by madindehead** [comment]
This is great - thank you.

That has worked and I understand now where to find the expressions on GitHub when I need them. Thank you again. I will close this issue for now, but if I have another more questions I will reply without re-opening.
