### ISSUE TITLE
Binder integrations broken

### ISSUE THREAD

**Issue by davidwagner** [data-8/textbook#176]
The interactive Binder integrations are broken.

Go to a page on inferentialthinking.com, click on the spaceship icon at the top, and click on "Binder". This eventually takes you an error page that says "500 : Internal Server Error" and gives no other useful feedback.

**Comment by sean-morris** [comment]
I am seeing this error as well. 

Here is the original link from the spaceship "Binder" link:
https://mybinder.org/v2/gh/data-8/textbook/main?urlpath=tree/chapters/07/1/Visualizing_Categorical_Distributions.ipynb

The branch is set to main which seems correct.

The 500 Error appears, this is the link copied from the "Copy Binder link" button:
https://mybinder.org/v2/gh/data-8/textbook/3a16ff69c7b80d9ff0b31d62aea03a4647fe3de2

If you take this link it opens up in the "lab" view:
https://mybinder.org/v2/gh/data-8/textbook/main

**Comment by davidwagner** [comment]
Fixed now, see #184

**Comment by davidwagner** [comment]
Closing
