### ISSUE TITLE
Exporting notebooks with images and data

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#2]
A common problem with the "Interact" links from last semester was that they didn't carry over access to images or datasets that were stored as separate files. We need to solve this problem.  Here are some solutions:

1) We add an export step that converts a source notebook into a publishable notebook by making all links to images and datasets absolute web addresses. Then, the notebook will refer to canonical image and data locations no matter where it is. Good: each notebook is still just a single file; Bad: if images are moved/removed, the notebook is broken

2) We add an export step that generates a `git sparse-checkout` command for each notebook. The sparse checkout includes the notebook and the image/data directories on which it depends. The "Interact" link causes our Jupyterhub server to execute the sparse checkout, so that all the dependencies are copied along with the notebook. Good: no need to modify notebooks & everything is self-contained

I like option 2. It does require that we rewrite how "Interact" works to be `git`-based instead of file based, but we should do that anyway. It also requires that we keep `gitbook-text` public, but I like that idea.

**Comment by papajohn** [comment]
I think this issue is nearly complete, but maybe we need to update interact links to point to `data8.berkeley.edu` in the right way.

**Comment by SamLau95** [comment]
Yeah, I can work on that.
