### ISSUE TITLE
Reconfigure hub target

### ISSUE THREAD

**Issue by ryanlovett** [data-8/textbook#32]
In a data8x discussion, @deculler expressed a desire to 1) enable other institutions to easily alter target of the Interact links and 2) set mybinder as the default Interact target for inferentialthinking.com. This means that there would not be secondary Interact buttons (as in #30). I'm posting this issue to solicit feedback from @papajohn and @a-adhikari. Cc'ing @yuvipanda who was part of the discussion.

Some implementation possibilities:
 - DNS; _institution_.inferentialthinking.com. Would require a human-maintained registry to map the domain name to a hub.
 - query string params to set a cookie; inferentialthinking.com?hub=top_level_hub_url
 - gitbook widget; with or without predefined hubs

Thoughts?

**Comment by ryanlovett** [comment]
Some followup questions from @yuvipanda via an email thread:

> 1. Who is responsible for maintaining inferentialthinking.com now?
> 
> 2. Where is it currently hosted?
> 
> 3. Who has rights to do things to it?
> 
> 4. Do we want to be long term responsible for hosting multiple versions of it? (whatever.inferentialthinking.org)

**Comment by papajohn** [comment]
On Tue, Jan 2, 2018 at 11:05 AM Ryan Lovett <notifications@github.com>
wrote:

> Some followup questions from @yuvipanda <https://github.com/yuvipanda>
> via an email thread:
>
>
>    1.
>
>    Who is responsible for maintaining inferentialthinking.com now?
>
>
I am.


>    1.
>
>    2.
>
>    Where is it currently hosted?
>
>
Gitbooks hosts, I think. Sam Lau set it up.

>
>    1.
>
>    2.
>
>    Who has rights to do things to it?
>
>
Sam Lau at least. I probably do too.

>
>    1.
>
>    2.
>
>    Do we want to be long term responsible for hosting multiple versions
>    of it? (whatever.inferentialthinking.org)
>
>
Yes. As long as the versions of just the same text pointing to different
places, then I think that should be no problem for us to host them all
along with some mechanism for spawning new ones.

**Comment by davidwagner** [comment]
This all seems to have been taken care of by the subsequent development work; schools can use the mechanisms found in https://berkeleydsep.gitbook.io/zero-to-data-8/deploying-data-8/set-up-your-course-website-and-textbook and https://github.com/data-8/zero-to-data-8/blob/master/misc/custom_textbook.md.
