### ISSUE TITLE
Enable ebook/pdf download

### ISSUE THREAD

**Issue by fperez** [data-8/textbook#39]
Printing to PDF from the browser doesn't work at all (a single-page PDF results with the image of a scroll bar).  From reading the [gitbook help](https://help.gitbook.com/books/how-can-i-provide-a-pdf-version-of-my-book.html) it seems to me that ebook download needs to be enabled from the config.

It would be great to be able to download a PDF build easily, sometimes I do need to print a few pages for paper-based reading...

**Comment by choldgraf** [comment]
Now that the textbook is building off of Jekyll + GH-Pages, I think this is now fixed so I'm closing, please do re-open if the "print to PDF" doesn't work!
