### ISSUE TITLE
Textbook doesn't load in gitbooks editor

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#4]
I tried `https://www.gitbook.com/book/ds8/textbook/edit`, but got 

    An unexpected error occurred when trying to load your book: Error 0:

Maybe it's related to the fact that we moved `dsten` -> `data-8`. Any ideas, @SamLau95 ?

**Comment by SamLau95** [comment]
Looks like the link is working after I updated the gitbook settings from dsten to data-8.

**Comment by papajohn** [comment]
Yep! works for me now. Thanks.

**Comment by ruiyuLee** [comment]
help! where the "dsten -> data-8"?
