### ISSUE TITLE
Pages based on notebooks changed URLs

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#45]
If possible, the path to

https://www.inferentialthinking.com/chapters/01/3/Plotting_the_Classics

should instead be

https://www.inferentialthinking.com/chapters/01/3/plotting-the-classics.html

 in order to preserve old links from previous course sites.

It looks like pages based on a Markdown file are fine, but those based on a notebook changed paths.

**Comment by papajohn** [comment]
I will soon learn enough to fix this kind of thing myself, but you can probably fix it more quickly for now, and we've broken some of the links on data8.org/su18. Thanks!

**Comment by wiltonwu** [comment]
+1 textbook links for the Data 8X edX online course have also been broken.

**Comment by choldgraf** [comment]
I fixed this last night - is it still broken?

**Comment by choldgraf** [comment]
There are a couple of links that are still broken in there (specifically, ones where in the old setup, the Jupyter Notebook file was called something different from the Markdown file). If you spot any of these ping me and we can fix quickly.

**Comment by choldgraf** [comment]
OK I believe this is now resolved, so going to close. If anybody finds a broken link w/ the same issue, feel free to reopen!
