### ISSUE TITLE
Textbook PDF is 290MB

### ISSUE THREAD

**Issue by SamLau95** [data-8/textbook#6]
Good news: The textbook is now able to build to PDF, Mobi, and ePub!

Bad news: The PDF is 290MB big. Interestingly, the Mobi and ePub versions are about 5MB.

My guess to the size difference is that the PDF has huge map images in the Privacy/License plate exploration. That's located at page 107 in the PDF and page 285 in the ePub.

**Comment by SamLau95** [comment]
Okay, by removing the Privacy exploration the PDF size is now 8MB. Until we can get maps rending properly we'll leave it out.

[staging-computational-and-inferential-thinking (1).pdf](https://files.zenhub.io/56a800b4d3f0602127596f8f)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[staging-computational-and-inferential-thinking (1).pdf](https://files.zenhub.io/56a800bfd3f0602127596f91)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by travisfw** [comment]
I can't find the epub, and for some reason the zip and tar downloads keep timing out. (Not my usual github experience.) Is there an epub download link somewhere?
