### ISSUE TITLE
Building Properties_of_the_Mean drops the $$'s

### ISSUE THREAD

**Issue by davidwagner** [data-8/textbook#64]
When I build `notebooks/14/1/Properties_of_the_Mean.ipynb` with `make textbook` to compile to `_chapters/14/1/Properties_of_the_Mean.md`, it drops the `$$` signs at the start and end of the `$$\begin{align*}...\end{align*}$$` section, and then that equation shows up as Latex gobbedygook rather than as formatted mathematics.

Not sure if this is just my build environment.  @choldgraf, do you see this too?

**Comment by choldgraf** [comment]
I'll take a look at it later today or tomorrow - been in NYC for a conference and just flying home now!

**Comment by davidwagner** [comment]
Cool.  No particular hurry.  Thank you!

**Comment by davidwagner** [comment]
Checking back in about this.  Any ideas?

**Comment by choldgraf** [comment]
just checking into this now - I see what you mean...this seems like a regression somehow, since the .md file from before *did* have those symbols...lemme look into it now

**Comment by choldgraf** [comment]
ah - it looks like the problem is that the `$$` are gone from the *jupyter notebook*, so this isn't a build problem. Can you confirm that your Jupyter Notebook for this page doesn't have the `$$` in it around that section?

**Comment by choldgraf** [comment]
digging into this more, it seems like the `$$` were removed a little while back because we activated `processEnvironments` in the mathjax configuration, which **should** convert things that start with `\begin` into TeX. However, this isn't happening and I'm not sure why.
