### ISSUE TITLE
Privacy Notebook results in huge PDF sizes

### ISSUE THREAD

**Issue by SamLau95** [data-8/textbook#7]
Adding in the privacy notebook to chapter 2 results in huge PDFs being rendered from Gitbook because the map images get way oversized.

After removing the notebook in ebada3cd9cc6ee2e7fbfe91a4e9720decdfeb31d the PDF size dropped from 290MB to 9MB.

We should figure out a way to get the maps images to render properly in PDF.

**Comment by davidwagner** [comment]
I'm not sure we render PDFs any longer, or have any way to create PDFs, so I think this might be a bit out of date.
