### ISSUE TITLE
Convert the textbook build to the new `jupyter-book` structure

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#74]
Recently @SamLau95 and I have been making improvements to the Jupyter-Book build structure. It's more lightweight now, and simpler to build and configure. It's also got some nicer features under-the-hood. Here's the DS100 repo built on it:

https://www.textbook.ds100.org/

and the jupyter-book demo:

http://predictablynoisy.com/jupyter-book/

I'm thinking about converting the data-8 build over to this system as well. Anybody have any objection to this?

**Comment by davidwagner** [comment]
I have no objections.  Would be interesting to see a pull request.

**Comment by choldgraf** [comment]
@davidwagner see #75
