### ISSUE TITLE
Customize interact links to include data

### ISSUE THREAD

**Issue by papajohn** [data-8/textbook#8]
We need a mechanism for customizing the interact links that are generated so that they include checking out the data associated with a notebook. E.g., the `Charts.ipynb` notebook needs `kaiser_ethnicity_everyone.csv` and `kaiser_ethnicity_children.csv`, but I'm not sure how to transfer them.

**Comment by SamLau95** [comment]
https://github.com/data-8/textbook/commit/f1bd49fcf76dc73939dd7acfeea93a9144c4b9cf looks for `read_table` calls and extracts out the dependencies into the interact link accordingly.

It looks like the interact at http://www.inferentialthinking.com/chapter2/charts.html has the CSV files.

**Comment by papajohn** [comment]
Amazing!
