### ISSUE TITLE
Indentation in code cells

### ISSUE THREAD

**Issue by davidwagner** [data-8/textbook#86]
The first line of every code cell is indented a little bit.  This causes code to not line up.

<img src="https://i.imgur.com/XK52gc4.png"/>

Here it is with a red vertical line added to make the indentation more obvious:

<img src="https://i.imgur.com/7Q9mwXD.png"/>

**Comment by davidwagner** [comment]
I checked the styles in Firefox Inspector, and I couldn't see any obvious CSS style that would be causing it.  I checked the computed value of the `text-indent` style, and it seems to be at `0px`, so presumably that's not it.  The above example was taken from https://www.inferentialthinking.com/chapters/13/2/Bootstrap, but it seems to be consistent throughout the textbook.

**Comment by choldgraf** [comment]
ok I think it's fixed - nice catch @davidwagner !

BTW - I see there are a bunch of changes lately - just making sure that these are happening at *both* `data-8/textbook` and `inferentialthinking/inferentialthinking.github.io`...is that true?

**Comment by davidwagner** [comment]
Awesome - thank you for the fix @SamLau95!  Yes, I've been pushing them to inferentialthinking, @choldgraf.  Thanks for the build system -- it works out great!
