### ISSUE TITLE
A new (simpler) build process for the textbook

### ISSUE THREAD

**Issue by choldgraf** [data-8/textbook#95]
Hey all - I just worked with @yuvipanda to remove a few unnecessary steps from the build process for updating the data-8 textbook. Here are the new instructions

https://github.com/data-8/textbook#how-this-repository-is-deployed-to-inferentialthinkingcom

Here's the summary:
* Old way
  * Make changes in data-8/textbook and build the site
  * Push to data-8/textbook
  * `cd` into your local repository for `github.com/interentialthinking/inferentialthinking.github.io`
  * `git pull` the latest changes from the `textbook` repository
  * `git push` the changes to the `inferentialthinking.github.io` repository

* New way
  * Make changes in data-8/textbook and build the site
  * Push to data-8/textbook
  * Changes are auto-deployed by `circleci` to the `inferentialthinking.github.io` repository.

Let me know if you have questions or thoughts! cc @davidwagner @a-adhikari @papajohn so you know about the new system.

This should close the issues in #82 and #83. I'll leave this issue open for a couple weeks and will then close all of them unless we surface other problems

**Comment by yuvipanda** [comment]
@choldgraf awesome! Would love to have a writeup of the process so others using jupyter book can also set this up easily.

**Comment by choldgraf** [comment]
working on it :-)

**Comment by choldgraf** [comment]
writeup is here: https://predictablynoisy.com/circleci-mirror

closing this now!
