### ISSUE TITLE
Funky issue with negatives, dollar signs, mathjax in Central Limit Theoreom

### ISSUE THREAD

**Issue by pamelafox** [data-8/textbook#96]
From here:
https://www.inferentialthinking.com/chapters/14/4/Central_Limit_Theorem

It starts "Center. The distribution is centered near" and then formatting gets confused:

<img width="872" alt="screen shot 2018-11-29 at 8 11 44 pm" src="https://user-images.githubusercontent.com/297042/49268205-0299f400-f413-11e8-82cb-5715a16d7d2b.png">

I'm not sure what the intended formatting is for the numbers with dollar signs, so I haven't sent a PR for this one.

**Comment by davidwagner** [comment]
Seems to have been fixed since then. Thanks for letting us know!
