### ISSUE TITLE
Copy to clipboard button displaying incorrectly

### ISSUE THREAD

**Issue by vivrekar** [data-8/textbook#98]
On Chrome and Safari, the _Copy to Clipboard_ button on some pages of the textbook seems to be formatted incorrectly. The screenshot below from is from §1.3 in Chrome.

<img width="716" alt="copy to clipboard button" src="https://user-images.githubusercontent.com/25167018/50678410-6932a480-0fb3-11e9-9aa5-ffd89104f939.png">

On Safari, the view is a bit different (screenshot below).
<img width="670" alt="safari copy to clipboard" src="https://user-images.githubusercontent.com/25167018/50678467-a9922280-0fb3-11e9-9c2e-e9f815580c2a.png">

Hovering over the little rectangle in the top right corner makes the `Copy` button appear as below.
<img width="667" alt="mouse over" src="https://user-images.githubusercontent.com/25167018/50678491-c890b480-0fb3-11e9-966f-71a9a81a4830.png">

**Comment by davidwagner** [comment]
It looks fine to me in Safari on iOS.  Are you still seeing this problem?

**Comment by davidwagner** [comment]
It looks fine for me on Safari and Chrome on Mac OS X, too.  I suspect this might have gotten fixed since it was reported by other changes we've made, so I'll close it, but if you still encounter it, let us know so we can investigate further.  Thanks for your report.
